<a href="https://colab.research.google.com/github/DarvinX/SEFR/blob/main/sefr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sefr

  Created wheel for sefr: filename=sefr-1.0.2-py3-none-any.whl size=2493 sha256=751fa5745c8efbbfbf2addb6644ee9f5d04a8de813b0a8d39bed2b9a6c67a6bf
  Stored in directory: /root/.cache/pip/wheels/96/54/23/770e6ca91c9e0f291d4d8ec0591e3a0d886c13d1034e927329
Successfully built sefr


In [2]:
!pip install micromlgen

  Created wheel for micromlgen: filename=micromlgen-1.1.25-py3-none-any.whl size=29265 sha256=23edad1611fc606b5b9dd8a584039dcb4aea1aea6d8587b4a22fcb89da43df23
  Stored in directory: /root/.cache/pip/wheels/4c/04/0b/b9c3c8a2b292df181c153640d8fde4b8c280c22a3afbcebd0c
Successfully built micromlgen


In [3]:
import numpy as np
from glob import glob
from os.path import basename

def load_features(folder):
    dataset = None
    classmap = {}
    for class_idx, filename in enumerate(glob('%s/*.csv' % folder)):
        class_name = basename(filename)[:-4]
        classmap[class_idx] = class_name
        samples = np.loadtxt(filename, dtype=float, delimiter=',')
        labels = np.ones((len(samples), 1)) * class_idx
        samples = np.hstack((samples, labels))
        dataset = samples if dataset is None else np.vstack((dataset, samples))

    return dataset, classmap

In [135]:
from sefr import SEFR
from micromlgen import port
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# put your samples in the dataset folder
# one class per file
# one feature vector per line, in CSV format
features, classmap = load_features('dataset/')

X, y = features[:, :-1], features[:, -1]

# Normalise
for i in range(len(X)):
  mx = max(X[i])
  mn = min(X[i])
  denom = mx-mn
  for j in range(len(X[i])):
    X[i][j] = (X[i][j] - mn)/denom

print(X)
print(y)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
clf = SEFR()
# clf = RandomForestClassifier(n_estimators=25, max_depth=10)
# clf = SVC(kernel='linear', gamma=0.001)

# print(clf.fit(X_train, y_train))
clf.fit(X, y)

# predicted = clf.predict(X_test)
# for i in range(len(y_test)):
#   print(int(y_test[i]), predicted[i])
# print('accuracy', (predicted == y_test).sum() / len(y_test))

[[0.60784314 0.59577677 0.55957768 ... 0.58371041 0.58371041 0.58371041]
 [0.69       0.69       0.61       ... 0.63666667 0.63666667 0.63666667]
 [0.44308943 0.44308943 0.42682927 ... 0.42682927 0.42682927 0.44308943]
 ...
 [0.44       0.44       0.44       ... 0.43058824 0.43058824 0.44      ]
 [0.55172414 0.55172414 0.52873563 ... 0.52873563 0.52873563 0.52873563]
 [0.49595687 0.4851752  0.49595687 ... 0.4851752  0.49595687 0.4851752 ]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [136]:
c_code = port(clf, classmap=classmap)
print(c_code)

#pragma once
#include <cstdarg>
namespace Eloquent {
    namespace ML {
        namespace Port {
            class SEFR {
                public:
                    /**
                    * Predict class for features vector
                    */
                    int predict(float *x) {
                        return dot(x,   -0.058489968919  , -0.056083812086  , -0.053455021645  , -0.091426224575  , -0.055563724607  , -0.037923365224  , -0.052383224726  , -0.042991786827  , -0.079121160187  , -0.058123423745  , -0.06924355523  , -0.043309116071  , -0.06032393108  , -0.075933702683  , -0.081973051514  , -0.063130544543  , -0.066982598634  , -0.096508001264  , -0.055951434558  , -0.102076425258  , -0.082859589735  , -0.080112492522  , -0.07354176818  , -0.022153483141  , -0.050141764875  , -0.153398431078  , -0.134863887294  , -0.109126065283  , -0.004010613665  , -0.18237116085  , -0.206643438565  , -0.165540514958  , -0.058690915401  , -0.106038381  , -0.092483647624  , -0.085609